language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - sh bin/setup.sh
  - pip install coveralls

script:
  - sh bin/coverage.sh

after_success:
  - coverage html
  - coveralls
