language: python
python:
  - "3.4"
  - "3.5"
  - "pypy3"

matrix:
  allow_failures:
    - python: pypy3

install:
  - sh bin/setup.sh
  - pip install coveralls

script:
  - sh bin/coverage.sh

after_success:
  - coverage html
  - coveralls
