pg_data:
  image: busybox
  volumes:
    - "/var/lib/postgresql"

db:
  image: postgres
  volumes_from:
    - pg_data

web:
  build: .
  command: docker-entrypoint
  volumes:
    - ./code:/code
    - ./media:/web-media
  ports:
    - "8000:8000"
  links:
    - db
  environment:
    DJANGO_SETTINGS_MODULE: settings.docker
