version: '3'

services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: ./bin/docker-entrypoint.sh
    volumes:
      - .:/code
      - ./media:/web-media
    ports:
      - "8000:8000"
    depends_on:
      - db
