version: '3'
services:
  db:
    image: postgres:9.5
  web:
    build: .
    command: ./bin/docker-entrypoint.sh
    volumes:
      - ./media:/web-media
      - ./static:/static
    ports:
      - "7238:8000"
    environment:
      DJANGO_SETTINGS_MODULE: settings.production
    env_file:
      - ../production.env
    depends_on:
      - db
