pg_data:
  image: busybox
  volumes:
    - "/var/lib/postgresql"

db:
  image: postgres
  volumes_from:
    - pg_data

web:
  build: .
  command: docker-entrypoint
  links:
    - db
  ports:
    - "7283:7283"
    - "9191:7284" 
  volumes:
    - ./media:/web-media
    - ./static:/static
  environment:
    DJANGO_SETTINGS_MODULE: settings.production
  env_file:
    - ./code/settings/production.env
