# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:46
from __future__ import unicode_literals

import app.validators
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0028_auto_20151227_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatype',
            name='available_options',
            field=jsonfield.fields.JSONField(default='{\n    "properties":\n    {\n        "id": {\n            "title": "ID",\n            "type": "integer"\n            }\n    },\n    "required": ["id"]\n}', help_text='A JSON schema of options that the media type allows', validators=[app.validators.json_schema_validator]),
        ),
    ]
