# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:36
from __future__ import unicode_literals

import app.validators
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name="Base Provider's name")),
                ('available_options', jsonfield.fields.JSONField(default='{\n    "properties":\n    {\n        "id": {\n            "title": "ID",\n            "type": "integer"\n            }\n    },\n    "required": ["id"]\n}', help_text='A JSON Schema of options that the base provider allows', validators=[app.validators.json_schema_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Name of the provider')),
                ('website', models.URLField(help_text="url to the provider's website", verbose_name="Provider's website")),
                ('regex_find_count', models.CharField(default='\\d+', help_text='Regular expression used client side to extract the episode/chapter count from a file name', max_length=256)),
                ('options', jsonfield.fields.JSONField(blank=True, default={}, help_text="JSON Object filled of BaseProvider's available_options with data")),
                ('base_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.BaseProvider')),
            ],
        ),
    ]
