# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 05:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0012_auto_20150706_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='options',
            field=jsonfield.fields.JSONField(help_text="JSON Object filled of BaseProvider's available_options with data"),
        ),
    ]
