# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 09:44
from __future__ import unicode_literals

import app.validators
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0015_auto_20160114_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprovider',
            name='available_options',
            field=jsonfield.fields.JSONField(default='{\n    "properties":\n    {\n        "id": {\n            "title": "ID",\n            "type": "integer"\n            }\n    },\n    "required": ["id"]\n}', help_text='A JSON Schema of options that the base provider allows', validators=[app.validators.json_schema_validator]),
        ),
    ]
