# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 09:50
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_auto_20151227_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='options',
            field=jsonfield.fields.JSONField(blank=True, help_text="JSON Object filled of BaseProvider's available_options with data"),
        ),
    ]
